title: "CESM2-LE on AWS"
logo: images/cesm.jpg
execute:
  execute_notebooks: "off"
html:
  extra_footer: |
    <p>
    By Science @ Scale Team <br>
    Â© Copyright 2021, National Center for Atmospheric Research.
    </p>
sphinx:
  config:
    html_show_copyright: false
